### PR TITLE
[Android] Changed PathFromUri method to work for newer android versions.

### PR DESCRIPTION
**Pull request by Gr33nMayhem**
Hi,

I have made the changes needed to allow picking media files from newer android versions. This should reduce the cache usage of the unity application as it won't have to copy the media file to a temporary location.

### CODE REVIEW

**Comment by yasirkula** [comment]
I've heard that the method used in that code isn't working for files that are in subdirectories of Downloads. Can you move the music file to `/storage/emulated/0/Downloads/Test/fileName.mp3` (**inside Test subdirectory**) and see if your current solution still works? I'm guessing that it won't. You might suggest that it's better to return a path when the file is at least a direct child of Downloads directory but then, if the fileName.mp3 file exists both inside Downloads/ and Downloads/Test/ and the user selects Downloads/Test/fileName.mp3, the code will return Downloads/fileName.mp3 which would be extremely bad.

After doing the above test, could you also replace NativeGallery.aar with the one inside [this zip archive](https://github.com/yasirkula/UnityNativeGallery/files/9844043/NativeGallery.zip) and try again for both Downloads/fileName.mp3 and Downloads/Test/fileName.mp3?

**Comment by Gr33nMayhem** [comment]
Sure thing, I'll test it out and let you know.

**Comment by Gr33nMayhem** [comment]
I tested out with the code that I had provided and when I tried to get an audio file from a subfolder named 'test' in Downloads, the URI was:
content://com.android.providers.downloads.documents/document/msf%3A318]
this probably didn't fit into any of the if conditions in my case and the audio file got cached at:
/storage/emulated/0/Android/data/com.GreenMayhem.BeatNinja/cache/pickedMedia.mp3

This is actually problematic for my use case so I'll have to look into it and try to fix it :P

I tried using the new AAR file that you sent, and the files were cached in both cases (Downloads/test/audio.mp3 and Downloads/audio.mp3).

**Comment by yasirkula** [comment]
How about the AAR inside [this zip archive](https://github.com/yasirkula/UnityNativeGallery/files/9891437/NativeGallery.zip)?

**Comment by Gr33nMayhem** [comment]
Yea, for the new AAR file that you sent in your zip archive, the audio file was cached in both cases.

**Comment by yasirkula** [comment]
Hmm, if neither of the AARs that I've sent worked for you, then I'm currently out of ideas 😭 I guess Android did a very good job at hiding the downloaded files' paths.

**Comment by Gr33nMayhem** [comment]
Hahaha, yea that's true. If I can figure it out, I'll make a new AAR and send it to you with the code!

**Pull request closed without merging**
